repos:
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v2.0.1
  hooks:
  - id: dbt-docs-generate
  - id: check-model-has-tests-by-name
    name: Check that marketing marts have primary key tests
    files: ^models/marts/marketing/
    args: ["--tests", "unique=1", "data=1", "--"]