default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: suka.test
      # User/password auth
      user: 92736ah3AG
      password: "{{ env_var('PASSWORD') }}"
      role: accountadmin
      database: analytics
      warehouse: transforming
      schema: staging
      threads: 1
      client_session_keep_alive: False