name: Pre-commit checks

on:
  pull_request:
    branches:
      - main

jobs:
  dbt_checkpoint:
    runs-on: ubuntu-latest
    env:      
      ACCOUNT: ${{ vars.ACCOUNT }}
      DATABASE: ${{ vars.DATABASE }}
      SCHEMA: ${{ vars.SCHEMA }}
      USER: ${{ vars.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ROLE: ${{ vars.ROLE }}
      WAREHOUSE: ${{ vars.WAREHOUSE }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # Updated to v3

      - name: Set Up Python
        uses: actions/setup-python@v3 # Updated to v3
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install dbt-snowflake pre-commit

      - name: Install requirements
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - name: Run dbt checkpoint
        uses: dbt-checkpoint/action@v0.1
        with:
          extra_args: --files ${{ steps.get_file_changes.outputs.files}}
          dbt_version: 1.6.3
          dbt_adapter: dbt-snowflake