name: Pre-commit checks

on:
  pull_request:
    branches:
      - main

jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: cb11892.west-europe.azure
      SNOWFLAKE_USER: 92736ah3AG
      SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SF_PASSWORD }}
      SNOWFLAKE_ROLE: accountadmin
      SNOWFLAKE_SCHEMA: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # Updated to v3

      - name: Set Up Python
        uses: actions/setup-python@v3 # Updated to v3
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install dbt-snowflake pre-commit data-diff

      - name: Install dbt dependencies
        run: dbt deps

      - name: dbt build
        run: dbt build --full-refresh --profiles-dir ./

      - name: Run pre-commit checks
        run: pre-commit run --all-files 