version: 2

sources:
  - name: jaffle_shop
    description: This is a replicate of postgres db used by jaffle shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: one record per customer
      - name: orders
        description: one record per order includes cancelled and deleted

  - name: stripe
    description: Stripe payment log
    database: raw
    schema: stripe
    tables:
      - name: payment
        description: records for payments with method, payment id and orderid as reference 